import type { Commodity, Country, PlayerObjective, Shock } from './types';

// ── Commodities ──
export const COMMODITIES: Commodity[] = [
  { id: 'oil', name: 'Oil', globalBasePrice: 70, currentGlobalPrice: 70, supply: 1000, demand: 1000, volatility: 0.35, transportCost: 5, strategicImportance: 5, storageLimit: 200, category: 'energy', unit: 'bbl' },
  { id: 'gas', name: 'Natural Gas', globalBasePrice: 40, currentGlobalPrice: 40, supply: 800, demand: 800, volatility: 0.30, transportCost: 8, strategicImportance: 4, storageLimit: 150, category: 'energy', unit: 'mcf' },
  { id: 'wheat', name: 'Wheat', globalBasePrice: 25, currentGlobalPrice: 25, supply: 1200, demand: 1200, volatility: 0.25, transportCost: 3, strategicImportance: 5, storageLimit: 300, category: 'food', unit: 'ton' },
  { id: 'food', name: 'Food', globalBasePrice: 30, currentGlobalPrice: 30, supply: 1000, demand: 1000, volatility: 0.15, transportCost: 3, strategicImportance: 4, storageLimit: 200, category: 'food', unit: 'ton' },
  { id: 'steel', name: 'Steel', globalBasePrice: 50, currentGlobalPrice: 50, supply: 900, demand: 900, volatility: 0.20, transportCost: 6, strategicImportance: 3, storageLimit: 250, category: 'metal', unit: 'ton' },
  { id: 'copper', name: 'Copper', globalBasePrice: 60, currentGlobalPrice: 60, supply: 700, demand: 700, volatility: 0.28, transportCost: 5, strategicImportance: 3, storageLimit: 200, category: 'metal', unit: 'ton' },
  { id: 'electronics', name: 'Electronics', globalBasePrice: 100, currentGlobalPrice: 100, supply: 600, demand: 600, volatility: 0.22, transportCost: 4, strategicImportance: 4, storageLimit: 150, category: 'tech', unit: 'unit' },
  { id: 'machinery', name: 'Machinery', globalBasePrice: 80, currentGlobalPrice: 80, supply: 700, demand: 700, volatility: 0.18, transportCost: 7, strategicImportance: 3, storageLimit: 120, category: 'industrial', unit: 'unit' },
];

export function getCommodity(id: string): Commodity { return COMMODITIES.find(c => c.id === id)!; }

// ── Countries (real-world) ──
export const COUNTRIES: Country[] = [
  {
    id: 'saudi-arabia', name: 'Saudi Arabia', currency: 'SAR', currencyName: 'Saudi Riyal',
    currencyValue: 3.75, fxReserves: 800, goldReserves: 150, gdp: 2500, debt: 1200,
    debtToGDP: 0.48, inflation: 4.5, population: 45, economicSize: 1.0,
    exports: {}, imports: {}, tradeBalance: 0, exportRevenue: 0, importCost: 0,
    production: [
      { commodityId: 'oil', production: 120, productionCost: 25, capacity: 150 },
      { commodityId: 'gas', production: 90, productionCost: 18, capacity: 110 },
      { commodityId: 'steel', production: 30, productionCost: 55, capacity: 40 },
      { commodityId: 'wheat', production: 15, productionCost: 40, capacity: 20 },
    ],
    consumption: [
      { commodityId: 'machinery', consumption: 40, required: true },
      { commodityId: 'food', consumption: 35, required: true },
      { commodityId: 'electronics', consumption: 20, required: true },
      { commodityId: 'steel', consumption: 10, required: false },
    ],
    inventory: [{ commodityId: 'oil', quantity: 60 },{ commodityId: 'gas', quantity: 40 },{ commodityId: 'food', quantity: 30 },{ commodityId: 'machinery', quantity: 10 }],
    aiPersonality: 'export-maximizer', riskTolerance: 0.6,
    aiWeights: { economicGrowth: 0.25, tradeBalance: 0.20, domesticSupplySecurity: 0.15, fxReserveStability: 0.15, exportRevenue: 0.20, inflationControl: 0.05 },
    economicScore: 0, supplyChainResilience: 0, tradePartners: [], supplierConcentration: {}, inCrisis: false, isHuman: false,
  },
  {
    id: 'japan', name: 'Japan', currency: 'JPY', currencyName: 'Japanese Yen',
    currencyValue: 1.10, fxReserves: 1200, goldReserves: 200, gdp: 4000, debt: 1800,
    debtToGDP: 0.45, inflation: 2.0, population: 80, economicSize: 1.5,
    exports: {}, imports: {}, tradeBalance: 0, exportRevenue: 0, importCost: 0,
    production: [
      { commodityId: 'electronics', production: 100, productionCost: 70, capacity: 130 },
      { commodityId: 'machinery', production: 80, productionCost: 60, capacity: 100 },
      { commodityId: 'steel', production: 20, productionCost: 70, capacity: 30 },
    ],
    consumption: [
      { commodityId: 'oil', consumption: 50, required: true },
      { commodityId: 'gas', consumption: 40, required: true },
      { commodityId: 'copper', consumption: 35, required: true },
      { commodityId: 'food', consumption: 40, required: true },
    ],
    inventory: [{ commodityId: 'oil', quantity: 30 },{ commodityId: 'gas', quantity: 25 },{ commodityId: 'copper', quantity: 30 },{ commodityId: 'food', quantity: 25 },{ commodityId: 'electronics', quantity: 40 }],
    aiPersonality: 'industrializer', riskTolerance: 0.5,
    aiWeights: { economicGrowth: 0.25, tradeBalance: 0.15, domesticSupplySecurity: 0.25, fxReserveStability: 0.15, exportRevenue: 0.15, inflationControl: 0.05 },
    economicScore: 0, supplyChainResilience: 0, tradePartners: [], supplierConcentration: {}, inCrisis: false, isHuman: false,
  },
  {
    id: 'brazil', name: 'Brazil', currency: 'BRL', currencyName: 'Brazilian Real',
    currencyValue: 5.50, fxReserves: 400, goldReserves: 80, gdp: 1200, debt: 600,
    debtToGDP: 0.50, inflation: 6.0, population: 60, economicSize: 0.6,
    exports: {}, imports: {}, tradeBalance: 0, exportRevenue: 0, importCost: 0,
    production: [
      { commodityId: 'wheat', production: 150, productionCost: 15, capacity: 180 },
      { commodityId: 'food', production: 100, productionCost: 18, capacity: 130 },
    ],
    consumption: [
      { commodityId: 'oil', consumption: 25, required: true },
      { commodityId: 'gas', consumption: 15, required: false },
      { commodityId: 'machinery', consumption: 20, required: true },
      { commodityId: 'electronics', consumption: 10, required: false },
    ],
    inventory: [{ commodityId: 'wheat', quantity: 80 },{ commodityId: 'food', quantity: 60 },{ commodityId: 'oil', quantity: 15 }],
    aiPersonality: 'security-first', riskTolerance: 0.3,
    aiWeights: { economicGrowth: 0.15, tradeBalance: 0.15, domesticSupplySecurity: 0.35, fxReserveStability: 0.15, exportRevenue: 0.10, inflationControl: 0.10 },
    economicScore: 0, supplyChainResilience: 0, tradePartners: [], supplierConcentration: {}, inCrisis: false, isHuman: false,
  },
  {
    id: 'chile', name: 'Chile', currency: 'CLP', currencyName: 'Chilean Peso',
    currencyValue: 2.80, fxReserves: 600, goldReserves: 120, gdp: 1800, debt: 900,
    debtToGDP: 0.50, inflation: 5.0, population: 30, economicSize: 0.8,
    exports: {}, imports: {}, tradeBalance: 0, exportRevenue: 0, importCost: 0,
    production: [
      { commodityId: 'copper', production: 100, productionCost: 35, capacity: 120 },
      { commodityId: 'steel', production: 70, productionCost: 45, capacity: 90 },
      { commodityId: 'gas', production: 30, productionCost: 35, capacity: 40 },
    ],
    consumption: [
      { commodityId: 'food', consumption: 30, required: true },
      { commodityId: 'electronics', consumption: 15, required: true },
      { commodityId: 'machinery', consumption: 25, required: true },
      { commodityId: 'oil', consumption: 15, required: false },
    ],
    inventory: [{ commodityId: 'copper', quantity: 50 },{ commodityId: 'steel', quantity: 40 },{ commodityId: 'food', quantity: 20 }],
    aiPersonality: 'diversifier', riskTolerance: 0.4,
    aiWeights: { economicGrowth: 0.20, tradeBalance: 0.20, domesticSupplySecurity: 0.20, fxReserveStability: 0.15, exportRevenue: 0.15, inflationControl: 0.10 },
    economicScore: 0, supplyChainResilience: 0, tradePartners: [], supplierConcentration: {}, inCrisis: false, isHuman: false,
  },
  {
    id: 'germany', name: 'Germany', currency: 'EUR', currencyName: 'Euro',
    currencyValue: 0.92, fxReserves: 1000, goldReserves: 180, gdp: 3500, debt: 2000,
    debtToGDP: 0.57, inflation: 3.0, population: 70, economicSize: 1.3,
    exports: {}, imports: {}, tradeBalance: 0, exportRevenue: 0, importCost: 0,
    production: [
      { commodityId: 'machinery', production: 90, productionCost: 55, capacity: 110 },
      { commodityId: 'steel', production: 60, productionCost: 50, capacity: 80 },
      { commodityId: 'electronics', production: 40, productionCost: 80, capacity: 55 },
    ],
    consumption: [
      { commodityId: 'oil', consumption: 55, required: true },
      { commodityId: 'copper', consumption: 30, required: true },
      { commodityId: 'food', consumption: 45, required: true },
      { commodityId: 'gas', consumption: 25, required: false },
    ],
    inventory: [{ commodityId: 'oil', quantity: 35 },{ commodityId: 'copper', quantity: 25 },{ commodityId: 'machinery', quantity: 30 },{ commodityId: 'steel', quantity: 25 }],
    aiPersonality: 'trader', riskTolerance: 0.5,
    aiWeights: { economicGrowth: 0.20, tradeBalance: 0.20, domesticSupplySecurity: 0.15, fxReserveStability: 0.15, exportRevenue: 0.20, inflationControl: 0.10 },
    economicScore: 0, supplyChainResilience: 0, tradePartners: [], supplierConcentration: {}, inCrisis: false, isHuman: false,
  },
  {
    id: 'new-zealand', name: 'New Zealand', currency: 'NZD', currencyName: 'New Zealand Dollar',
    currencyValue: 1.60, fxReserves: 350, goldReserves: 60, gdp: 600, debt: 300,
    debtToGDP: 0.50, inflation: 3.5, population: 12, economicSize: 0.3,
    exports: {}, imports: {}, tradeBalance: 0, exportRevenue: 0, importCost: 0,
    production: [{ commodityId: 'food', production: 35, productionCost: 25, capacity: 45 }],
    consumption: [
      { commodityId: 'oil', consumption: 20, required: true },
      { commodityId: 'gas', consumption: 10, required: true },
      { commodityId: 'food', consumption: 25, required: true },
      { commodityId: 'electronics', consumption: 8, required: false },
      { commodityId: 'machinery', consumption: 8, required: false },
    ],
    inventory: [{ commodityId: 'oil', quantity: 15 },{ commodityId: 'food', quantity: 25 }],
    aiPersonality: 'reserve-defender', riskTolerance: 0.2,
    aiWeights: { economicGrowth: 0.10, tradeBalance: 0.15, domesticSupplySecurity: 0.25, fxReserveStability: 0.30, exportRevenue: 0.10, inflationControl: 0.10 },
    economicScore: 0, supplyChainResilience: 0, tradePartners: [], supplierConcentration: {}, inCrisis: false, isHuman: false,
  },
  {
    id: 'qatar', name: 'Qatar', currency: 'QAR', currencyName: 'Qatari Riyal',
    currencyValue: 3.64, fxReserves: 500, goldReserves: 100, gdp: 1500, debt: 800,
    debtToGDP: 0.53, inflation: 4.0, population: 35, economicSize: 0.7,
    exports: {}, imports: {}, tradeBalance: 0, exportRevenue: 0, importCost: 0,
    production: [
      { commodityId: 'gas', production: 60, productionCost: 30, capacity: 80 },
      { commodityId: 'steel', production: 40, productionCost: 55, capacity: 50 },
    ],
    consumption: [
      { commodityId: 'oil', consumption: 30, required: true },
      { commodityId: 'food', consumption: 25, required: true },
      { commodityId: 'machinery', consumption: 20, required: true },
      { commodityId: 'electronics', consumption: 12, required: false },
      { commodityId: 'copper', consumption: 10, required: false },
    ],
    inventory: [{ commodityId: 'gas', quantity: 35 },{ commodityId: 'oil', quantity: 20 },{ commodityId: 'food', quantity: 20 }],
    aiPersonality: 'protectionist', riskTolerance: 0.35,
    aiWeights: { economicGrowth: 0.15, tradeBalance: 0.20, domesticSupplySecurity: 0.30, fxReserveStability: 0.15, exportRevenue: 0.10, inflationControl: 0.10 },
    economicScore: 0, supplyChainResilience: 0, tradePartners: [], supplierConcentration: {}, inCrisis: false, isHuman: false,
  },
  {
    id: 'vietnam', name: 'Vietnam', currency: 'VND', currencyName: 'Vietnamese Dong',
    currencyValue: 6.50, fxReserves: 300, goldReserves: 50, gdp: 800, debt: 500,
    debtToGDP: 0.63, inflation: 7.0, population: 55, economicSize: 0.4,
    exports: {}, imports: {}, tradeBalance: 0, exportRevenue: 0, importCost: 0,
    production: [
      { commodityId: 'food', production: 50, productionCost: 22, capacity: 65 },
      { commodityId: 'copper', production: 25, productionCost: 50, capacity: 35 },
    ],
    consumption: [
      { commodityId: 'oil', consumption: 20, required: true },
      { commodityId: 'machinery', consumption: 15, required: true },
      { commodityId: 'electronics', consumption: 10, required: true },
      { commodityId: 'steel', consumption: 15, required: true },
      { commodityId: 'wheat', consumption: 15, required: false },
    ],
    inventory: [{ commodityId: 'food', quantity: 40 },{ commodityId: 'oil', quantity: 12 }],
    aiPersonality: 'trader', riskTolerance: 0.55,
    aiWeights: { economicGrowth: 0.25, tradeBalance: 0.20, domesticSupplySecurity: 0.20, fxReserveStability: 0.10, exportRevenue: 0.15, inflationControl: 0.10 },
    economicScore: 0, supplyChainResilience: 0, tradePartners: [], supplierConcentration: {}, inCrisis: false, isHuman: false,
  },
];

// ── Shocks Pool ──
export const SHOCK_POOL: Omit<Shock, 'effects' | 'affectedCountries' | 'affectedCommodities'>[] = [
  { id: 's1', name: 'Oil Price Collapse', description: 'Global oil prices fall sharply.', category: 'commodity-price', severity: 'major', newsHeadline: 'Oil prices crash as major producers flood the market.' },
  { id: 's2', name: 'Oil Price Surge', description: 'Oil prices spike due to supply disruption.', category: 'commodity-price', severity: 'major', newsHeadline: 'Oil prices surge after Saudi production disruption.' },
  { id: 's3', name: 'Tech Boom', description: 'Global electronics demand surges.', category: 'demand', severity: 'moderate', newsHeadline: 'Global electronics demand increases 14%.' },
  { id: 's4', name: 'Global Recession', description: 'Industrial demand drops sharply.', category: 'demand', severity: 'major', newsHeadline: 'Global recession reduces industrial demand by 30%.' },
  { id: 's5', name: 'Drought', description: 'Severe drought reduces global wheat production.', category: 'production', severity: 'major', newsHeadline: 'Drought reduces global wheat production by 25%.' },
  { id: 's6', name: 'Bumper Harvest', description: 'Exceptional weather boosts food production.', category: 'production', severity: 'minor', newsHeadline: 'Record harvest pushes food prices lower.' },
  { id: 's7', name: 'Strait Closure', description: 'A major maritime route is closed.', category: 'supply-chain', severity: 'crisis', newsHeadline: 'Major maritime route closed — shipping costs surge.' },
  { id: 's8', name: 'Currency Crisis: Saudi Arabia', description: 'Saudi Riyal experiences sharp depreciation.', category: 'exchange-rate', severity: 'major', newsHeadline: 'Saudi Riyal depreciates 18% amid capital outflows.' },
  { id: 's9', name: 'Currency Rally: Japan', description: 'Japanese Yen strengthens significantly.', category: 'exchange-rate', severity: 'moderate', newsHeadline: 'Yen gains 8% after strong export data.' },
  { id: 's10', name: 'Tech Export Ban', description: 'Japan restricts electronics exports.', category: 'sanction', severity: 'major', newsHeadline: 'Japan imposes export restrictions on advanced electronics.' },
  { id: 's11', name: 'Copper Export Quota', description: 'Chile introduces copper export restrictions.', category: 'political', severity: 'moderate', newsHeadline: 'Chile announces copper export quotas.' },
  { id: 's12', name: 'Wheat Export Ban', description: 'Brazil restricts wheat exports.', category: 'political', severity: 'moderate', newsHeadline: 'Brazil restricts wheat exports.' },
  { id: 's13', name: 'Shipping Cost Spike', description: 'Container shipping costs rise dramatically.', category: 'shipping', severity: 'moderate', newsHeadline: 'Shipping costs increase 45% across the Eastern Corridor.' },
  { id: 's14', name: 'Gas Pipeline Disruption', description: 'Natural gas pipeline suffers major disruption.', category: 'supply-chain', severity: 'major', newsHeadline: 'Gas pipeline disruption hits supply to Germany and Japan.' },
  { id: 's15', name: 'Food Price Spike', description: 'Food prices rise sharply.', category: 'commodity-price', severity: 'moderate', newsHeadline: 'Food prices jump 20% on supply fears.' },
  { id: 's16', name: 'Steel Overcapacity', description: 'Global steel production exceeds demand.', category: 'commodity-price', severity: 'minor', newsHeadline: 'Steel prices fall as global overcapacity weighs.' },
  { id: 's17', name: 'Copper Discovery', description: 'New copper deposits discovered.', category: 'production', severity: 'minor', newsHeadline: 'Major copper discovery promises to boost global supply.' },
  { id: 's18', name: 'Electronics Supply Glut', description: 'Electronics production outpaces demand.', category: 'demand', severity: 'minor', newsHeadline: 'Electronics prices dip as supply outpaces demand.' },
  { id: 's19', name: 'Trade Agreement', description: 'Bilateral trade deal reduces tariffs.', category: 'political', severity: 'minor', newsHeadline: 'New trade agreement signed, boosting bilateral trade.' },
  { id: 's20', name: 'Energy Transition', description: 'Global shift toward renewables reduces gas demand.', category: 'demand', severity: 'moderate', newsHeadline: 'Renewable energy push dampens natural gas demand.' },
  { id: 's21', name: 'Shipping Route Reopens', description: 'A previously disrupted shipping route reopens.', category: 'shipping', severity: 'minor', newsHeadline: 'Key shipping route reopens, easing trade flows.' },
  { id: 's22', name: 'Machinery Boom', description: 'Industrial machinery demand surges.', category: 'demand', severity: 'moderate', newsHeadline: 'Global machinery demand jumps as infrastructure spending rises.' },
  { id: 's23', name: 'Saudi Sanctions', description: 'International sanctions target Saudi Arabia.', category: 'sanction', severity: 'crisis', newsHeadline: 'New sanctions target Saudi Arabia, disrupting energy trade.' },
  { id: 's24', name: 'Debt Crisis', description: 'Sovereign debt concerns shake currency markets.', category: 'exchange-rate', severity: 'major', newsHeadline: 'Debt concerns trigger currency volatility.' },
  { id: 's25', name: 'Tech Innovation', description: 'Breakthrough reduces electronics production costs.', category: 'production', severity: 'minor', newsHeadline: 'Tech innovation lowers electronics production costs globally.' },
];

// ── Player Objectives ──
export const OBJECTIVES: PlayerObjective[] = [
  { id: 'obj1', name: 'Export Powerhouse', description: 'Increase exports by 40%', target: 40, current: 0, completed: false, metric: 'exportGrowth' },
  { id: 'obj2', name: 'Currency Defender', description: 'Keep currency depreciation under 10%', target: 10, current: 0, completed: false, metric: 'currencyDepreciation' },
  { id: 'obj3', name: 'Trade Diversifier', description: 'No supplier > 35% of imports', target: 35, current: 100, completed: false, metric: 'maxSupplierShare' },
  { id: 'obj4', name: 'Industrial Expansion', description: 'Increase machinery production 30%', target: 30, current: 0, completed: false, metric: 'machineryGrowth' },
  { id: 'obj5', name: 'Crisis Survivor', description: 'Maintain essential inventories above 60%', target: 60, current: 100, completed: false, metric: 'minInventoryLevel' },
  { id: 'obj6', name: 'Reserve Builder', description: 'Increase FX reserves by 25%', target: 25, current: 0, completed: false, metric: 'reserveGrowth' },
];
